preload = ~/Documents/Backgrounds/batman_vertical.jpg
preload = ~/Documents/Backgrounds/lotr.jpg

wallpaper {
    monitor = DP-1
    path = ~/Documents/Backgrounds/batman_vertical.jpg
    fit_mode = fill
}

wallpaper {
    monitor = DP-3
    path = ~/Documents/Backgrounds/lotr.jpg
    fit_mode = cover
}
