wallpaper {
    monitor = DP-1
    path = /home/jgarner/Documents/Backgrounds/batman_vertical.jpg
    fit_mode = fill
}

wallpaper {
    monitor = DP-3
    path = /home/jgarner/Documents/Backgrounds/lotr.jpg
    fit_mode = cover
}
