return {
  "williamboman/mason.nvim",
  opts = {
    ensure_installed = {
      "ruff",
      "mypy",
      "eslint_d",
      "luacheck",
      "html",
      "cssls",
      "ts_ls",
      "gopls",
      "clangd",
      "pyright",
      "htmx-lsp",
      "stylua",
      "prettier",
      "prettierd",
      "goimports",
      "gofmt",
      "isort",
      "black",
      "clang-format",
      "codespell",
      "trim_whitespace",
    },
  },
}
